### ISSUE TITLE
cartridge-cli does not start application

### ISSUE THREAD

**Issue by artembo** [tarantool/cartridge-docker#8]
Steps to reproduce:
- docker pull tarantool/cartridge
- docker run --rm -it tarantool/cartridge bash
- cartridge create --name demo
- cd demo
  (btw, there's no instances.yml in `demo` folder)
- cartridge start demo
then cartridge stuck on this message:
```
[root@52abff024205 demo]# cartridge start demo
Starting demo...
```

**Comment by artur-barsegyan** [comment]
What will be if you add any `instances.yml` file with topology information?

**Comment by artembo** [comment]
I tried but nothing changes.

**Comment by knazarov** [comment]
Latest version of the container has support for cartridge-start in templates, but it doesn't work due to a bug in cartridge-cli. Let's wait for newer cartridge-cli, then close this issue

**Comment by artembo** [comment]
I've just run new image and `cartridge start` works fine.
Thanks!
